#       0          10        20       30
#       01234567890123456789012345678901234
cadena="la floja de Karla no quiere caminar"

#EJERCIOIO 1
print(cadena[23]) #DEBE MOSTRAR LA LETRA i

#EJERCIOIO 2
print(cadena[3]) #DEBE MOSTRAR LA LETRA f

#EJERCIOIO 3
print(cadena[34]) #DEBE MOSTRAR LA LETRA r

#EJERCIOIO 4
print(cadena[6]) #DEBE MOSTRAR LA LETRA j

#EJERCIOIO 5
print(cadena[5]) #DEBE MOSTRAR LA LETRA o

#EJERCIOIO 6
print(cadena[7]) #DEBE MOSTRAR LA LETRA a

#EJERCIOIO 7
print(cadena[1]) #DEBE MOSTRAR LA LETRA a

#EJERCIOIO 8
print(cadena[10]) #DEBE MOSTRAR LA LETRA e

#EJERCIOIO 9
print(cadena[12]) #DEBE MOSTRAR LA LETRA K

#EJERCIOIO 10
print(cadena[2]) #DEBE MOSTRAR EL ESPACIO " "

#EJERCIOIO 11
print(cadena[26]) #DEBE MOSTRAR LA LETRA e

#EJERCIOIO 12
print(cadena[7]) #DEBE MOSTRAR LA LETRA a

#EJERCIOIO 13
print(cadena[5]) #DEBE MOSTRAR LA LETRA o

#EJERCIOIO 14
print(cadena[31]) #DEBE MOSTRAR LA LETRA i

#EJERCIOIO 15
print(cadena[20]) #DEBE MOSTRAR ESPACIO EN BLANCO " "

